"""
Career Agent for AI v2 module.

Recommends suitable career paths based on user profile and market data.
Uses LLM for intelligent recommendation generation.
"""

from typing import Any, Dict

from ..schemas import AgentOutput, AgentType
from ..services import LLMService
from .base_agent import BaseAgent


class CareerAgent(BaseAgent):
    """
    Agent responsible for career recommendation.
    
    Purpose:
        - Use LLM to generate personalized career recommendations
        - Match user skills with career opportunities
        - Score and rank career options
        - Consider user preferences and constraints
        - Provide detailed career information
    
    LLM Integration:
        - Uses OpenAI GPT-4 for recommendations (with mock fallback)
        - Generates structured career suggestions
        - Includes match scores and market data
    
    TODO:
        - Build job market knowledge base (RAG)
        - Add market demand scoring  
        - Filter careers by user preferences
        - Query salary and growth trends
        - EXPERIMENTAL: Multi-agent debate for career consensus
    """

    def __init__(self):
        """Initialize the CareerAgent."""
        super().__init__(
            agent_type=AgentType.CAREER,
            name="Career Recommender",
        )
        self.llm = LLMService()

    def run(self, input_data: Dict[str, Any]) -> AgentOutput:
        """
        Generate career recommendations using LLM.
        
        Args:
            input_data (Dict[str, Any]): Must contain:
                - user_profile: UserProfile object
                - (optional) cv_data: CV analysis results
                - (optional) preferences: Career preferences
        
        Returns:
            AgentOutput: Career recommendations with match scores
        
        Example:
            >>> agent = CareerAgent()
            >>> result = agent.run({"user_profile": profile})
            >>> print(result.data["recommended_careers"])
        """
        try:
            self._log_execution("Starting career recommendation with LLM")

            user_profile = input_data.get("user_profile")
            cv_data = input_data.get("cv_data", {})
            preferences = input_data.get("preferences", {})
            
            if not user_profile:
                raise ValueError("user_profile is required")
            
            # Extract skills from profile and CV
            user_skills = user_profile.current_skills or []
            cv_skills = cv_data.get("skills_extracted", [])
            all_skills = list(set(user_skills + cv_skills))
            
            # Get market data (for future RAG integration)
            job_market_data = input_data.get("job_market_data")
            
            # Use LLM to generate recommendations
            llm_result = self.llm.generate_recommendations(
                user_profile={
                    "experience_level": user_profile.experience_level,
                    "education": user_profile.education,
                    "preferences": preferences,
                },
                user_skills=all_skills,
                job_market_data=job_market_data,
                count=3,  # Generate 3 recommendations
            )
            
            if not llm_result.get("success"):
                raise ValueError("LLM failed to generate recommendations")
            
            # Structure career recommendations
            recommended_careers = llm_result.get("recommended_careers", [])
            
            career_recommendations = {
                "recommended_careers": recommended_careers,
                "primary_recommendation": recommended_careers[0] if recommended_careers else None,
                "confidence_score": llm_result.get("confidence_score", 0.75),
                "reasoning": llm_result.get("reasoning", "Generated by AI"),
                "user_skills": all_skills,
            }
            
            self._log_execution(
                f"Career recommendation completed - {len(recommended_careers)} careers recommended"
            )
            
            return self._create_output(
                success=True,
                data=career_recommendations,
            )

        except Exception as e:
            self._log_execution(f"Error during career recommendation: {str(e)}", level="error")
            return self._create_output(
                success=False,
                error=str(e),
            )
