"""Chatbot tools registry.

Automatically exposes all @tool-decorated functions to graph nodes and
generates OpenAI-compatible tool manifests for LLM tool calling.
"""
import inspect
from typing import Any, Callable, Dict, List, Optional

from langchain_core.tools import BaseTool

# Booking tools
from app.agents.chatbot.tools.booking import (
    check_mentor_availability,
    get_available_mentors,
    find_mentor_by_name,
    book_mentor_session,
    get_user_sessions,
    get_mentor_details,
)

# Search tools
from app.agents.chatbot.tools.search import (
    web_search,
    search_career_info,
    get_job_trends,
    get_career_recommendations_info,
    explain_career,
)

# General tools
from app.agents.chatbot.tools.general import (
    get_user_profile,
    get_app_features,
    get_career_recommendations,
    explain_app_feature,
)

# Profile tools
from app.agents.chatbot.tools.profile import (
    get_user_full_profile,
    get_my_career_matches,
)


ALL_TOOLS: List[Callable] = [
    # Booking
    check_mentor_availability,
    get_available_mentors,
    find_mentor_by_name,
    book_mentor_session,
    get_user_sessions,
    get_mentor_details,
    # Search
    web_search,
    search_career_info,
    get_job_trends,
    get_career_recommendations_info,
    explain_career,
    # General
    get_user_profile,
    get_app_features,
    get_career_recommendations,
    explain_app_feature,
    # Profile
    get_user_full_profile,
    get_my_career_matches,
]


_TOOL_MANIFEST: List[Dict[str, Any]] = []


def get_tool_manifest() -> List[Dict[str, Any]]:
    """Return an OpenAI-compatible tool manifest for all chatbot tools.

    Caches the manifest after first call to avoid repeated introspection.
    """
    global _TOOL_MANIFEST
    if _TOOL_MANIFEST:
        return _TOOL_MANIFEST

    manifest: List[Dict[str, Any]] = []
    for tool_fn in ALL_TOOLS:
        if isinstance(tool_fn, BaseTool):
            manifest.append(base_tool_to_openai_schema(tool_fn))
        else:
            manifest.append(fn_to_openai_schema(tool_fn))

    _TOOL_MANIFEST = manifest
    return manifest


def get_tool_descriptions_block() -> str:
    """Return a markdown-formatted list of all tools for prompt injection."""
    lines = ["### Available Tools\n"]
    for tool_fn in ALL_TOOLS:
        if isinstance(tool_fn, BaseTool):
            name = tool_fn.name
            doc = (tool_fn.description or "").strip()
        else:
            name = getattr(tool_fn, "__name__", str(tool_fn))
            doc = inspect.getdoc(tool_fn) or ""
        lines.append(f'- **{name}**: {doc.replace(chr(10), " ")}')
    return "\n".join(lines)


BOOKING_TOOLS: List[Callable] = [
    check_mentor_availability,
    get_available_mentors,
    find_mentor_by_name,
    book_mentor_session,
    get_user_sessions,
    get_mentor_details,
]


def get_booking_tool_descriptions_block() -> str:
    """Return a markdown-formatted list of booking-related tools only."""
    lines = ["### Available Booking Tools\n"]
    for tool_fn in BOOKING_TOOLS:
        if isinstance(tool_fn, BaseTool):
            name = tool_fn.name
            doc = (tool_fn.description or "").strip()
        else:
            name = getattr(tool_fn, "__name__", str(tool_fn))
            doc = inspect.getdoc(tool_fn) or ""
        lines.append(f'- **{name}**: {doc.replace(chr(10), " ")}')
    return "\n".join(lines)


def get_booking_tool_manifest() -> List[Dict[str, Any]]:
    """Return OpenAI-compatible tool manifest for booking tools only."""
    manifest: List[Dict[str, Any]] = []
    for tool_fn in BOOKING_TOOLS:
        if isinstance(tool_fn, BaseTool):
            manifest.append(base_tool_to_openai_schema(tool_fn))
        else:
            manifest.append(fn_to_openai_schema(tool_fn))
    return manifest


def find_tool_schema(name: str) -> Optional[Dict[str, Any]]:
    """Find a tool schema by name."""
    for schema in get_tool_manifest():
        if schema.get("function", {}).get("name") == name:
            return schema
    return None


def base_tool_to_openai_schema(tool: BaseTool) -> Dict[str, Any]:
    """Convert a LangChain BaseTool to OpenAI-compatible schema."""
    return {
        "type": "function",
        "function": {
            "name": tool.name,
            "description": tool.description or f"Tool: {tool.name}",
            "parameters": tool.args_schema.schema() if tool.args_schema else {
                "type": "object",
                "properties": {},
            },
        },
    }


def fn_to_openai_schema(fn: Callable) -> Dict[str, Any]:
    """Convert a @tool-decorated function to OpenAI-compatible schema.

    Uses the tool's internal schema (from @tool decorator) if available.
    """
    # Try to get the internal args schema generated by @tool
    schema = getattr(fn, "args_schema", None)
    if schema:
        params = schema.schema() if hasattr(schema, "schema") else dict(schema)
    else:
        params = {"type": "object", "properties": {}}

    description = inspect.getdoc(fn) or f"Tool: {getattr(fn, '__name__', str(fn))}"
    # Clean up docstring: take first paragraph only
    description = description.split("\n\n")[0].strip()

    return {
        "type": "function",
        "function": {
            "name": getattr(fn, "__name__", str(fn)),
            "description": description,
            "parameters": params,
        },
    }


__all__ = [
    "ALL_TOOLS",
    "BOOKING_TOOLS",
    "get_tool_manifest",
    "get_tool_descriptions_block",
    "get_booking_tool_manifest",
    "get_booking_tool_descriptions_block",
    "find_tool_schema",
    "check_mentor_availability",
    "get_available_mentors",
    "find_mentor_by_name",
    "book_mentor_session",
    "get_user_sessions",
    "get_mentor_details",
    "web_search",
    "search_career_info",
    "get_job_trends",
    "get_career_recommendations_info",
    "explain_career",
    "get_user_profile",
    "get_app_features",
    "get_career_recommendations",
    "explain_app_feature",
    "get_user_full_profile",
    "get_my_career_matches",
]
