import { User, Career, Skill, Course, Recommendation } from "@/types/career";

// Mock Users Data
export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "john.doe@example.com",
    name: "John Doe",
    role: "user",
    status: "active",
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-02-01T14:22:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    phone: "+1-555-0101",
  },
  {
    id: "user-2",
    email: "jane.smith@example.com",
    name: "Jane Smith",
    role: "user",
    status: "active",
    createdAt: "2024-01-20T09:15:00Z",
    updatedAt: "2024-02-03T11:45:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    phone: "+1-555-0102",
  },
  {
    id: "user-3",
    email: "mike.johnson@example.com",
    name: "Mike Johnson",
    role: "manager",
    status: "active",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-02-02T13:30:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
    phone: "+1-555-0103",
  },
  {
    id: "user-4",
    email: "sarah.williams@example.com",
    name: "Sarah Williams",
    role: "user",
    status: "inactive",
    createdAt: "2024-01-25T16:45:00Z",
    updatedAt: "2024-01-28T10:00:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
  },
  {
    id: "user-5",
    email: "admin@example.com",
    name: "Admin User",
    role: "admin",
    status: "active",
    createdAt: "2023-12-01T00:00:00Z",
    updatedAt: "2024-02-03T15:20:00Z",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Admin",
    phone: "+1-555-0105",
  },
];

// Mock Skills Data
export const mockSkills: Skill[] = [
  {
    id: "skill-1",
    name: "JavaScript",
    category: "Programming Languages",
    description: "JavaScript programming and ES6+ features",
    relatedCareers: ["career-1", "career-2"],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "skill-2",
    name: "React",
    category: "Frontend Frameworks",
    description: "React.js library for building user interfaces",
    relatedCareers: ["career-1"],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "skill-3",
    name: "Node.js",
    category: "Backend Frameworks",
    description: "Node.js runtime for server-side JavaScript",
    relatedCareers: ["career-2"],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "skill-4",
    name: "Python",
    category: "Programming Languages",
    description: "Python programming language",
    relatedCareers: ["career-3", "career-5"],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "skill-5",
    name: "Data Analysis",
    category: "Analytics",
    description: "Data analysis and visualization",
    relatedCareers: ["career-3"],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "skill-6",
    name: "Project Management",
    category: "Management",
    description: "Project and team management",
    relatedCareers: ["career-4"],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "skill-7",
    name: "Machine Learning",
    category: "AI & ML",
    description: "Machine learning and AI concepts",
    relatedCareers: ["career-5"],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "skill-8",
    name: "Cloud Computing",
    category: "Cloud Services",
    description: "AWS, Azure, and GCP cloud platforms",
    relatedCareers: ["career-2"],
    createdAt: "2024-01-01T00:00:00Z",
  },
];

// Mock Careers Data
export const mockCareers: Career[] = [
  {
    id: "career-1",
    title: "Frontend Developer",
    description: "Build user interfaces and client-side applications using modern web technologies",
    category: "Technology",
    requiredSkills: ["skill-1", "skill-2"],
    averageSalary: 95000,
    growthRate: 12,
    demandLevel: "very-high",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "career-2",
    title: "Backend Developer",
    description: "Develop server-side applications and APIs using various programming languages and frameworks",
    category: "Technology",
    requiredSkills: ["skill-1", "skill-3", "skill-8"],
    averageSalary: 105000,
    growthRate: 15,
    demandLevel: "very-high",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "career-3",
    title: "Data Scientist",
    description: "Analyze data, build predictive models, and provide insights for business decisions",
    category: "Technology",
    requiredSkills: ["skill-4", "skill-5", "skill-7"],
    averageSalary: 115000,
    growthRate: 25,
    demandLevel: "very-high",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "career-4",
    title: "Product Manager",
    description: "Define product strategy, manage roadmaps, and lead cross-functional teams",
    category: "Business",
    requiredSkills: ["skill-6"],
    averageSalary: 125000,
    growthRate: 10,
    demandLevel: "high",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "career-5",
    title: "AI/ML Engineer",
    description: "Design and implement machine learning models and AI solutions",
    category: "Technology",
    requiredSkills: ["skill-4", "skill-7"],
    averageSalary: 130000,
    growthRate: 35,
    demandLevel: "very-high",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "career-6",
    title: "UX/UI Designer",
    description: "Design beautiful and intuitive user experiences and interfaces",
    category: "Design",
    requiredSkills: [],
    averageSalary: 85000,
    growthRate: 14,
    demandLevel: "high",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "career-7",
    title: "DevOps Engineer",
    description: "Manage infrastructure, deployment pipelines, and system reliability",
    category: "Technology",
    requiredSkills: ["skill-8"],
    averageSalary: 110000,
    growthRate: 18,
    demandLevel: "high",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "career-8",
    title: "Cybersecurity Specialist",
    description: "Protect systems and data from security threats and vulnerabilities",
    category: "Technology",
    requiredSkills: [],
    averageSalary: 120000,
    growthRate: 20,
    demandLevel: "very-high",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
];

// Mock Courses Data
export const mockCourses: Course[] = [
  {
    id: "course-1",
    title: "React.js - The Complete Guide",
    provider: "Udemy",
    description: "Learn React with hooks, context API, and modern patterns",
    skillsTargeted: ["skill-1", "skill-2"],
    duration: "40 hours",
    level: "intermediate",
    url: "https://udemy.com/react-course",
    price: 99.99,
    rating: 4.8,
  },
  {
    id: "course-2",
    title: "The Complete Node.js Developer Course",
    provider: "Udemy",
    description: "Master Node.js, Express, and build real-world applications",
    skillsTargeted: ["skill-1", "skill-3"],
    duration: "50 hours",
    level: "intermediate",
    url: "https://udemy.com/nodejs-course",
    price: 99.99,
    rating: 4.7,
  },
  {
    id: "course-3",
    title: "Python for Data Science",
    provider: "Coursera",
    description: "Learn data analysis with Python, Pandas, and NumPy",
    skillsTargeted: ["skill-4", "skill-5"],
    duration: "30 hours",
    level: "beginner",
    url: "https://coursera.org/python-data-science",
    price: 49.99,
    rating: 4.6,
  },
  {
    id: "course-4",
    title: "Machine Learning Specialization",
    provider: "Coursera",
    description: "Master machine learning with Andrew Ng",
    skillsTargeted: ["skill-4", "skill-7"],
    duration: "100 hours",
    level: "advanced",
    url: "https://coursera.org/ml-specialization",
    price: 199.99,
    rating: 4.9,
  },
  {
    id: "course-5",
    title: "AWS Solutions Architect",
    provider: "A Cloud Guru",
    description: "Learn AWS architecture and cloud design patterns",
    skillsTargeted: ["skill-8"],
    duration: "60 hours",
    level: "advanced",
    url: "https://acloudguru.com/aws-architect",
    price: 79.99,
    rating: 4.7,
  },
  {
    id: "course-6",
    title: "Project Management Fundamentals",
    provider: "LinkedIn Learning",
    description: "Essential project management concepts and techniques",
    skillsTargeted: ["skill-6"],
    duration: "20 hours",
    level: "beginner",
    url: "https://linkedin.com/learning/project-management",
    price: 39.99,
    rating: 4.5,
  },
];

// Mock Recommendations Data
export const mockRecommendations: Recommendation[] = [
  {
    id: "rec-1",
    userId: "user-1",
    careers: [mockCareers[0], mockCareers[1]],
    courses: [mockCourses[0], mockCourses[1]],
    matchScore: 92,
    generatedAt: "2024-02-01T10:30:00Z",
    status: "viewed",
  },
  {
    id: "rec-2",
    userId: "user-2",
    careers: [mockCareers[2], mockCareers[4]],
    courses: [mockCourses[2], mockCourses[3]],
    matchScore: 88,
    generatedAt: "2024-02-02T14:15:00Z",
    status: "sent",
  },
  {
    id: "rec-3",
    userId: "user-3",
    careers: [mockCareers[3]],
    courses: [mockCourses[5]],
    matchScore: 85,
    generatedAt: "2024-02-03T09:00:00Z",
    status: "pending",
  },
];

// Dashboard Stats
export const mockDashboardStats = {
  totalUsers: 2547,
  activeSessions: 1234,
  totalRecommendations: 1650,
  conversionRate: 68.5,
  userGrowth: [
    { month: "Jan", users: 400 },
    { month: "Feb", users: 600 },
    { month: "Mar", users: 800 },
    { month: "Apr", users: 1200 },
    { month: "May", users: 1600 },
    { month: "Jun", users: 2000 },
    { month: "Jul", users: 2547 },
  ],
  careerRecommendationsByCategory: [
    { category: "Technology", count: 450 },
    { category: "Healthcare", count: 320 },
    { category: "Business", count: 280 },
    { category: "Education", count: 210 },
    { category: "Engineering", count: 390 },
  ],
  recommendationStatus: [
    { status: "pending", count: 450 },
    { status: "sent", count: 750 },
    { status: "viewed", count: 450 },
  ],
};
